export {default as Home} from './home'
export {default as Login} from './login'
export {default as Register} from './register'
export {default as MyRoutines} from './myroutines'
export {default as Activities }from './activities'
export {default as Rotuines} from './routines'
export {default as MakeRoutines} from './makeroutines'
export {default as EditRoutine} from './editroutine'